// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutra.API.Infrastructure;

#nullable disable

namespace Nutra.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125192806_UpdateDesafiosTable")]
    partial class UpdateDesafiosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Nutra.Domain.Entidades.Desafios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMeta")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("XpRecompensa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNivel");

                    b.HasIndex("IdTipoRegistro");

                    b.ToTable("Desafios", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Niveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("XpNecessario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Niveis", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Opcoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdPergunta")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdPergunta");

                    b.ToTable("Opcoes", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Perguntas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdQuestionario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdQuestionario");

                    b.ToTable("Perguntas", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Questionarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Questionarios", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Receitas", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagemBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Receitas", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Registros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdTipoRegistro")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoRegistro");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Observacao");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoRegistro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Registros", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Respostas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdOpcao")
                        .HasColumnType("int");

                    b.Property<int>("IdPergunta")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestionario")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdOpcao");

                    b.HasIndex("IdPergunta");

                    b.HasIndex("IdQuestionario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Respostas", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.TipoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Categoria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Descricao");

                    b.Property<string>("TipoDetalhe")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TipoDetalhe");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TiposRegistro", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Aluno");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("XpTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Desafios", b =>
                {
                    b.HasOne("Nutra.Domain.Entidades.Niveis", "Nivel")
                        .WithMany()
                        .HasForeignKey("IdNivel")
                        .IsRequired();

                    b.HasOne("Nutra.Domain.Entidades.TipoRegistro", "TipoRegistro")
                        .WithMany()
                        .HasForeignKey("IdTipoRegistro")
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("TipoRegistro");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Opcoes", b =>
                {
                    b.HasOne("Nutra.Domain.Entidades.Perguntas", "Perguntas")
                        .WithMany("OpcoesRespostas")
                        .HasForeignKey("IdPergunta")
                        .IsRequired();

                    b.Navigation("Perguntas");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Perguntas", b =>
                {
                    b.HasOne("Nutra.Domain.Entidades.Questionarios", "Questionarios")
                        .WithMany("Perguntas")
                        .HasForeignKey("IdQuestionario")
                        .IsRequired();

                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Registros", b =>
                {
                    b.HasOne("Nutra.Domain.Entidades.TipoRegistro", "Tipo")
                        .WithMany("Registros")
                        .HasForeignKey("IdTipoRegistro")
                        .IsRequired();

                    b.HasOne("Nutra.Domain.Entidades.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired();

                    b.Navigation("Tipo");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Respostas", b =>
                {
                    b.HasOne("Nutra.Domain.Entidades.Opcoes", "Opcoes")
                        .WithMany()
                        .HasForeignKey("IdOpcao")
                        .IsRequired();

                    b.HasOne("Nutra.Domain.Entidades.Perguntas", "Perguntas")
                        .WithMany()
                        .HasForeignKey("IdPergunta")
                        .IsRequired();

                    b.HasOne("Nutra.Domain.Entidades.Questionarios", "Questionarios")
                        .WithMany()
                        .HasForeignKey("IdQuestionario")
                        .IsRequired();

                    b.HasOne("Nutra.Domain.Entidades.Usuarios", "Usuarios")
                        .WithMany("Respostas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired();

                    b.Navigation("Opcoes");

                    b.Navigation("Perguntas");

                    b.Navigation("Questionarios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Perguntas", b =>
                {
                    b.Navigation("OpcoesRespostas");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Questionarios", b =>
                {
                    b.Navigation("Perguntas");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.TipoRegistro", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Nutra.Domain.Entidades.Usuarios", b =>
                {
                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
